services:
  postgres:
    image: postgres:16
    container_name: hardware-postgres
    restart: always
    environment:
      POSTGRES_DB: hardware
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - hardware_postgres_data:/var/lib/postgresql/data

volumes:
  hardware_postgres_data:
